#spring.application.name=251dswSpringBackendCotizacion
server:
  port:
    9094
spring:
  application:
    name: 251dswSpringBackendCotizacion
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-long-mode-acef70ys-pooler.sa-east-1.aws.neon.tech:5432/tallerCotizacionDb?sslmode=require
    username: neondswauto_owner
    password: npg_6GMjSy5wiCxb
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka/





